Feat/GitHub profile
esc-chula/tech-website pull request #24
Opened 2024-11-11 17:49 UTC by neennera

- create trpc api **aboutMember** route for fetching github information
- add next/image config, so Image tag could use `src` from external link

2024-11-12 05:46 UTC, ebonian requested changes

2024-11-12 05:46 UTC, ebonian commented on src/components/about/member-section.tsx
> +export interface GithubMemberProps {
แยกออกมาไว้ที่ `src/types/about.ts` เลยดีกว่า

2024-11-12 05:46 UTC, ebonian commented on src/components/common/member-button.tsx
> +    <Link
มันเป็น external link เพราะฉะนั้น prop ใน <Link ใส่
target="_blank"
rel="noopener noreferrer"
ด้วยนะ

2024-11-12 05:46 UTC, ebonian commented on src/server/api/routers/about_members.ts
ตั้งชื่อไฟล์เป็น abouts.ts ได้เลย + ชื่อ router เป็น aboutRouter เลยก้ได้ฮะ

2024-11-12 05:46 UTC, ebonian commented on src/server/api/routers/about_members.ts
> +    // if (!response.ok) {
ทำ error handling ไว้ก็ดีแล้วนะ

2024-11-12 05:46 UTC, ebonian commented on src/components/about/member-section.tsx
ลองดูตัวอย่างของ projects ได้ว่าเรา fetch ยังไง
มันจะเป็นประมาณว่าเราสร้าง container ที่มาครอบ component นี้ไว้สำหรับ fetch data เพื่อให้ตอนที่เอา container ไปใช้เราสามารถ suspense มันได้
ex. `src\components\about\projects-container.tsx`

2024-11-12 17:04 UTC, neennera commented on src/components/about/member-section.tsx
คือแค่เติม await new Promise ไปหรอคะ ๆ ใน branch develop มีแค่นั้นน

2024-11-12 17:51 UTC, ebonian commented on src/components/about/member-section.tsx
ตอยให้นะดิสละนะ

2024-11-13 04:55 UTC, ebonian commented on src/components/about/member-container.tsx
> +  await new Promise((resolve) => setTimeout(resolve, 2000));
ไม่ต้องมี timeout ตรงนี้แล้วก็ได้นะ
ที่มีคือแค่แบบตัวอย่างจำลองเวลาโหลดเฉยๆ

2024-11-13 04:55 UTC, ebonian commented on src/components/about/member-container.tsx
rename `member-container` -> `members-container`

2024-11-13 04:55 UTC, ebonian commented on src/components/about/member-loading.tsx
> +      {members.map((member, index) => (
ใช้ <Skeleton /> ดีกว่า ๆ
อยู่ใน `src\components\ui\skeleton.tsx`

2024-11-13 04:55 UTC, ebonian commented on src/components/about/member-section.tsx
> -export const MemberSection = () => {
`MemberSection` -> `MembersSection`

2024-11-13 04:55 UTC, ebonian commented on src/server/api/routers/about.ts
> +    }
ตรง return error ออกไปเหมือนกับใน qrcode ดีกว่านะ
เพราะว่าถ้าเรา throw error ใน serverside ฝั่ง client มันจะไม่รุ้ว่า error อะไรละ handle ไม่ได้

2024-11-13 04:55 UTC, ebonian commented on src/components/about/member-loading.tsx
rename `member-loading` -> `members-loading.tsx`

2024-11-13 04:55 UTC, ebonian commented on src/components/about/member-section.tsx
rename `member-section` -> `members-section`

2024-11-13 04:55 UTC, ebonian commented
susu kub 👍 👍

2024-11-13 06:28 UTC, ebonian approved these changes

2024-11-13 06:28 UTC, merged