Fix/qr code
esc-chula/tech-website pull request #31
Opened 2024-12-28 19:01 UTC by Yiwahpsp

- ย้ายไฟล์
- download with logo
- func create action

2025-01-09 09:13 UTC, ebonian requested changes

2025-01-09 09:13 UTC, ebonian commented on src/app/(app)/tools/qr-code-generator/page.tsx
> +          <div className="md:hidden">
อันนี้ขอแก้ design นิดนึง ไม่ต้อง "md:hidden" ก็ได้ จะได้ consistant จาก link shortener

2025-01-09 09:13 UTC, ebonian commented on src/app/(app)/tools/qr-code-generator/page.tsx
>            <Suspense>
ตรงนี้ทำ fallback ด้วย (อันนี้ตัวอย่าง link-shortener)
สร้าง component loading ใหม่เลย ๆ ใช้ skeleton

```tsx
<Suspense fallback={<LinksLoading />}>
    <LinksContainer />
</Suspense>
```

2025-01-09 09:13 UTC, ebonian commented on src/components/tools/qr-code-generator/qr-code-delete-dialog.tsx
> +            This action cannot be undone. This will permanently delete your
ฝากแก้คำหน่อย เดะพี่ไปแก้ของ link shortener ให้ ๆ

2025-01-09 20:05 UTC, Yiwahpsp commented on src/components/tools/qr-code-generator/qr-code-create-button.tsx
> +      form.reset();
Demo:

https://github.com/user-attachments/assets/d7937681-f564-449c-a8f8-0ee258cbcd0a

2025-01-10 06:49 UTC, Yiwahpsp commented
- making reset form after create qrcode successful.


https://github.com/user-attachments/assets/537ad37d-e507-4ef4-96d6-5134c8b57e95


- remove md:hidden in create button
- change sentence in delete qrcode dialog

![image](https://github.com/user-attachments/assets/fc047e19-43b3-402b-b54a-b20772a6f9db)

- using qrcode loading in suspense

![image](https://github.com/user-attachments/assets/a09843b0-89ba-4a8e-848c-a57f1ca245f1)

2025-01-13 08:05 UTC, ebonian requested changes
ตอนนี้มันเหมือนว่าเรามี dialog สองอันชะ ละ code มัน duplicated อยู่
คิดว่าเดี่ยวเราแยก component ออกมาอีกอันดีกว่าแล้วเดี่ยว parse prop ลงไป

เผื่องง
- เดะเราแยก component qr-code-dialog-content.tsx ออกมา
  ```tsx
    <DialogContent className="md:max-w-md">
       ...
  ```
- และก็แยก qr-code-dialog-trigger.tsx
  ละค่อยให้ใส่ prop เข้าไปให้เป็นแบบ button ปกติกับ ปุ่มใหญ่ ๆ ที่มีบวก (เอาง่าย ๆ คือรวมไปในไฟล์เดียวเลย)
- สุดท้ายแยก qr-code-dialog.tsx ออกมาและใช้ react context ให้เก็บ state open ไว้

ถ้างงบอกได้นะ

2025-01-17 14:36 UTC, Yiwahpsp commented
- use useContext in qr-code-create-dialog

2025-01-17 18:15 UTC, Yiwahpsp commented
- downlooad qrcode w/ logo on Firefox


https://github.com/user-attachments/assets/918aee0f-95be-4371-a93a-fc1dcd9d27e4

2025-01-17 18:45 UTC, ebonian requested changes
susu

2025-01-17 18:45 UTC, ebonian commented on src/components/tools/qr-code-generator/qr-code-create-dialog-trigger.tsx
> +'use client';
new line

2025-01-17 18:45 UTC, ebonian commented on src/components/tools/qr-code-generator/qr-code-create-dialog-trigger.tsx
> +  const { isShowButton } = useContext(CreateDialogContext);
new line

2025-01-17 18:45 UTC, ebonian commented on src/components/tools/qr-code-generator/qr-code-create-dialog.tsx
>  'use client';
new line

2025-01-17 18:45 UTC, ebonian commented on src/components/tools/qr-code-generator/qr-code-create-dialog.tsx
> +  const [open, setOpen] = useState<boolean>(false);
new line

2025-01-17 18:45 UTC, ebonian commented on src/components/tools/qr-code-generator/qr-code-create-dialog-trigger.tsx
> +  const { isShowButton } = useContext(CreateDialogContext);
เราเปลี่ยนจากเอา prop นี้มาจาก dialog trigger เป็นดึงจาก prop ของ component ตัวนี้แทนเลยดีกว่า
พยายามให้ context นี้มันมีหน้าที่แค่เก็บ state เปิด/ปิดพอ

2025-01-17 18:45 UTC, ebonian commented on src/app/(app)/tools/qr-code-generator/page.tsx
ตอนนี้เหมือนเรามี dialog content อยู่สองที่ใช่มะ เพราะเรามี component <QRCodeCreateDialog ... /> อยู่สองที่
เพราะฉะนั้นถ้า user กดเปิด dialog ปุ่มใดปุ่มนึงอะ state ที่เค้ากรอกไว้มันจะไม่เหมือนกัน
เราอาจจะต้องแยกเป็นเอา Dialog มาครอบทั้งหมด แล้วค่อยมี 2 trigger แทน
ex
```tsx
<>
  <BackButton href="/" />
  <QRCodeCreateDialog>
    <div className="flex w-full flex-col items-center gap-5 pb-10 pt-20 lg:gap-8 lg:pt-8">
      <Title className="hidden lg:inline">QR Code Generator</Title>
      <div className="flex w-full items-center justify-between">
        <h2 className="text-2xl font-medium">Your QR Codes</h2>
        <QRCodeCreateDialogTrigger variant="button" />
      </div>
      <div className="grid w-full grid-cols-1 gap-5 md:grid-cols-2 lg:grid-cols-3 lg:gap-8">
        <QRCodeCreateDialogTrigger variant="card" />
        <Suspense fallback={<QRCodeLoading />}>
          <QRCodesContainer />
        </Suspense>
      </div>
    </div>
  </QRCodeCraeteDialog>
</>
```

2025-01-17 18:45 UTC, ebonian commented on src/components/tools/qr-code-generator/qr-code-create-dialog-trigger.tsx
> +  const { isShowButton } = useContext(CreateDialogContext);
เปลี่ยน prop จาก boolean เป็น string แล้วเช็คเอาดีกว่า
เราจะได้ทำให้ component นี้ในอนาคตมันไม่ได้ fix แค่สองแบบแต่เป็นแบบอื่น ๆ ได้อีก
แนะนำว่าใช้ prop ชื่อ variant ละกัน ละก็กำหนดค่า string ไว้เลย
```tsx
interface QRCodeCreateDialogTriggerProps {
  variant: "button" | "card"
}
```
และก็ใช้ switch case ไรงี้ดูก้ได้นะ

2025-01-23 10:41 UTC, Yiwahpsp commented
- fix: create dialog qrcode


https://github.com/user-attachments/assets/4c162d29-4707-429b-b408-2559f0232d78

2025-01-23 15:48 UTC, ebonian requested changes

2025-01-23 15:48 UTC, ebonian commented on src/components/tools/qr-code-generator/qr-code-create-dialog-trigger.tsx
> +  return <>{renderTrigger()}</>;
ไม่ต้องทำเป็น component แล้วค่อย return ก็ได้

return ด้วย switch case ไปเลยๆ

```tsx
...
}) => {
  switch (variant) {
    case 'button':
      return (
        ...
      );
    case 'card':
      return (
        ...
      );
    default:
      return null;
  }
};
...
```

2025-01-24 09:09 UTC, merged